### ISSUE TITLE
ModuleNotFoundError: No module named "rlbot"

### ISSUE THREAD

**Issue by sout12** [NicEastvillage/AutoLeague2#7]
![image](https://user-images.githubusercontent.com/15899910/153457211-3e25cd1c-5e5d-4d70-aab7-77721e3878fc.png)

Not sure why it's giving me this, I have ran pip install rlbot then uninstalled rlbot and installed it again, any ideas?

**Comment by NicEastvillage** [comment]
Are you using the `gui-venv.bat`? Running `gui-venv.bat` opens a console that uses the RLBotGUI's python which has rlbot installed as well as other packages used by many bots.
